### ISSUE TITLE
Contact Verification page

### ISSUE THREAD

**Issue by kess78** [openprovider/OP-WHMCS7#55] opened 2019-09-23 13:02 UTC
Hey guys,
why don't you include a custom page to the module as described here ?
https://support.openprovider.eu/hc/en-us/articles/216649118-Customize-contact-verification-page-for-gTLDs

Unfortunately it's not possible (or at least not so easily) to create a custom WHMCS page with PHP code inside. The only documented method is for creating static custom pages as described here: https://developers.whmcs.com/advanced/creating-pages/

Thank you for taking that into consideration.

**Comment by soberoctober** [comment] 2020-06-16 06:47
Duplicate of #12

**Closed by soberoctober** 2020-06-16 06:47 UTC
Labels: feature request
