### ISSUE TITLE
[BUG]Issue after upgrade to WHMCS 8

### ISSUE THREAD

**Issue by dutchcg** [openprovider/OP-WHMCS7#99] opened 2020-10-01 13:10 UTC
After the upgrade of WHMCS to version 8 i can't edit permissions for the admin groups.
Below the steps and the error.

**To Reproduce**
1. Go to 'Manage Admins'
2. Click on 'Permissions'
3. Click on edit icon after the admingroup
4. Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

Error: Cannot use object of type OpenProvider\WhmcsRegistrar\Controllers\Hooks\Widgets\BalanceWidget as array in /var/www/vhosts/........................./admin/configadminroles.php:0
Stack trace:
#0 /var/www/vhosts/.........................../admin/configadminroles.php(0): load_admin_home_widgets()
#1 {main}

**Comment by maverick85** [comment] 2020-10-01 16:23
Hi,
I've come across this but I believe your steps to reproduce are wrong.

Under Manage Admins there are no permissions, only the Admins that can be edited and I get no errors.
However, going to:
System Settings > Administrator Roles & Permissions
and then try to edit any role, and gives an error:

```
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

To receive a more detailed error message, please enable Display Errors via General Settings. Learn more
```

**Comment by MrKoopie** [comment] 2020-10-01 18:14
Thank you for reporting. Unfortunately, this is an unfixed error in WHMCS. See https://whmcs.community/topic/301988-administrator-roles-error/

**Comment by markschrik** [comment] 2020-10-01 20:05
Is there already official support for WHMCS 8? OpenProvider Support told me this still has to arrive.

**Comment by maverick85** [comment] 2020-10-02 14:28
> Thank you for reporting. Unfortunately, this is an unfixed error in WHMCS. See https://whmcs.community/topic/301988-administrator-roles-error/

Hi @MrKoopie thank you for your reply.
However, the error I'm getting (in full, not truncated as in that link):

```
[Thu Oct 01 17:21:06.623643 2020] [proxy_fcgi:error] [pid 1822:tid 139776002873088] [client :39074]
AH01071: Got error 'PHP message: [WHMCS Application] ERROR:
Error: Cannot use object of type OpenProvider\\WhmcsRegistrar\\Controllers\\Hooks\\Widgets\\BalanceWidget as array in /var/www/html/whmcs/admin/configadminroles.php:0
Stack trace: #0 /var/www/html/whmcs/admin/configadminroles.php(0): load_admin_home_widgets()
#1 {main} {"exception":"[object] (Error(code: 0): Cannot use object of type OpenProvider\\\\WhmcsRegistrar\\\\Controllers\\\\Hooks\\\\Widgets\\\\BalanceWidget as array at /var/www/html/whmcs/admin/configadminroles.php:0)"} []', referer: https://whmcs.domain.com/admin/configadminroles.php
```

I cannot reproduce the same error in a vanilla test instance of WHMCS.

**Comment by MrKoopie** [comment] 2020-10-02 19:13
@maverick85 Although it is a different module, both errors is about a widget incorrectly parsed by WHMCS. This problem occurs even with their own official project module.

The related WHMCS task is CORE-15215.

**Comment by MrKoopie** [comment] 2020-10-03 12:41
@maverick85 please upgrade to WHMCS 8.0.1. [The issue has been fixed by WHMCS](https://docs.whmcs.com/Changelog:WHMCS_V8.0#Version_8.0.1_Release_1_.28Maintenance.29). The related WHMCS task is CORE-15215.

**Closed by MrKoopie** 2020-10-03 12:41 UTC
Labels: bug
