### ISSUE TITLE
[BUG] Missing mod_op_scheduled_domain_transfers table

### ISSUE THREAD

**Issue by NLLucifer** [openprovider/OP-WHMCS7#103] opened 2020-10-10 13:07 UTC
```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_whmcs.mod_op_scheduled_domain_transfers' doesn't exist in /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php:331
Stack trace:
#0 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php(331): PDO->prepare('select count(*)...')
#1 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php(664): Illuminate\Database\Connection->Illuminate\Database\{closure}('select count(*)...', Array)
#2 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#3 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php(339): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#4 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2202): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#5 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2190): Illuminate\Database\Query\Builder->runSelect()
#6 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2685): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2191): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#8 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2612): Illuminate\Database\Query\Builder->get(Array)
#9 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2540): Illuminate\Database\Query\Builder->aggregate('count', Array)
#10 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Eloquent/Builder.php(1403): Illuminate\Database\Query\Builder->count()
#11 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#12 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Eloquent/Model.php(1728): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'count', Array)
#13 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/Controllers/Admin/ScheduledDomainTransferController.php(95): Illuminate\Database\Eloquent\Model->__call('count', Array)
#14 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/Controllers/Admin/ScheduledDomainTransferController.php(55): OpenProvider\WhmcsDomainAddon\Controllers\Admin\ScheduledDomainTransferController->pagination('https://client....', Object(OpenProvider\WhmcsDomainAddon\Models\ScheduledDomainTransfer))
#15 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsDomainAddon\Controllers\Admin\ScheduledDomainTransferController->index(Array)
#16 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('index', Array)
#17 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/openprovider.php(75): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'scheduledDomain...')
#18 /home/admin/domains/itbear.nl/public_html/client/admin/addonmodules.php(0): openprovider_output(Array)
#19 {main}
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin_whmcs.mod_op_scheduled_domain_transfers' doesn't exist (SQL: select count(*) as aggregate from `mod_op_scheduled_domain_transfers`) in /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php:671
Stack trace:
#0 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Connection.php(339): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2202): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#3 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2190): Illuminate\Database\Query\Builder->runSelect()
#4 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2685): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2191): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#6 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2612): Illuminate\Database\Query\Builder->get(Array)
#7 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Query/Builder.php(2540): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Eloquent/Builder.php(1403): Illuminate\Database\Query\Builder->count()
#9 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 /home/admin/domains/itbear.nl/public_html/client/vendor/illuminate/database/Eloquent/Model.php(1728): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Illuminate\Database\Eloquent\Builder), 'count', Array)
#11 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/Controllers/Admin/ScheduledDomainTransferController.php(95): Illuminate\Database\Eloquent\Model->__call('count', Array)
#12 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/Controllers/Admin/ScheduledDomainTransferController.php(55): OpenProvider\WhmcsDomainAddon\Controllers\Admin\ScheduledDomainTransferController->pagination('https://client....', Object(OpenProvider\WhmcsDomainAddon\Models\ScheduledDomainTransfer))
#13 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsDomainAddon\Controllers\Admin\ScheduledDomainTransferController->index(Array)
#14 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(54): WeDevelopCoffee\wPower\Core\Instance->execute('index', Array)
#15 /home/admin/domains/itbear.nl/public_html/client/modules/addons/openprovider/openprovider.php(75): WeDevelopCoffee\wPower\Core\Launch->output(Array, 'scheduledDomain...')
#16 /home/admin/domains/itbear.nl/public_html/client/admin/addonmodules.php(0): openprovider_output(Array)
```

**Comment by wmetge** [comment] 2020-10-12 05:49
@NLLucifer thanks for reporting the issue. We'll investigate why the table is not being automatically created.

Meanwhile, as a workaround you can create it using this statement:

CREATE TABLE `tblDomainSyncOpenprovider` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `last_sync` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=96 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

I'm closing this ticket as a duplicate of https://github.com/openprovider/OP-WHMCS7/issues/102

**Comment by wmetge** [comment] 2020-10-12 11:57
@NLLucifer thank you for letting us know, we will release a solution within the week. Thank you for your patience.

**Comment by NLLucifer** [comment] 2020-10-12 11:58
Coolio. Thanks!

**Comment by markschrik** [comment] 2020-10-26 13:13
@wmetge any updates?

**Comment by wmetge** [comment] 2020-10-27 08:22
@markschrik @NLLucifer 
Please see the latest commit, it solves issues with the missing tables.

**Closed** 2020-11-06 15:30 UTC
Labels: bug

**Comment by muhsinozmen** [comment] 2021-01-21 00:16
Same issue here with latest version and whmcs 7.7.1

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'u5978p3984_portal.mod_op_scheduled_domain_transfers' doesn't exist in /xxx/public_html/portal/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /xxx/public_html/portal/vendor/illuminate/database/Connection.php(333): PDO->prepare('select * from `...')
#1 /xxx/public_html/portal/vendor/illuminate/database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 /xxx/public_html/portal/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 /xxx/public_html/portal/vendor/illuminate/database/Connection.php(342): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#4 /xxx/public_html/portal/vendor/illuminate/database/Query/Builder.php(1583): Illuminate\Database\Connection->select('select * from `...', Array, true)
#5 /xxx/public_html/portal/vendor/illuminate/database/Query/Builder.php(1569): Illuminate\Database\Query\Builder->runSelect()
#6 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(624): Illuminate\Database\Query\Builder->get(Array)
#7 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(316): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(286): Illuminate\Database\Eloquent\Builder->get(Array)
#9 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(299): Illuminate\Database\Eloquent\Builder->first(Array)
#10 /xxx/public_html/portal/modules/addons/openprovider/Controllers/Hooks/RenewHookController.php(132): Illuminate\Database\Eloquent\Builder->firstOrFail()
#11 /xxx/public_html/portal/modules/addons/openprovider/Controllers/Hooks/RenewHookController.php(192): OpenProvider\WhmcsDomainAddon\Controllers\Hooks\RenewHookController->checkScheduledTransferAtOpenprovider(Object(stdClass))
#12 /xxx/public_html/portal/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsDomainAddon\Controllers\Hooks\RenewHookController->processAutorenewalSetting(Array)
#13 /xxx/public_html/portal/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(93): WeDevelopCoffee\wPower\Core\Instance->execute('processAutorene...', Array)
#14 /xxx/public_html/portal/includes/hookfunctions.php(0): WeDevelopCoffee\wPower\Core\Launch->__call('hook_1', Array)
#15 /xxx/public_html/portal/beheer/clientsdomains.php(0): run_hook('DomainEdit', Array)
#16 {main}
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'u5978p3984_portal.mod_op_scheduled_domain_transfers' doesn't exist (SQL: select * from `mod_op_scheduled_domain_transfers` where `domain` = remoprojecten.nl limit 1) in /xxx/public_html/portal/vendor/illuminate/database/Connection.php:713
Stack trace:
#0 /xxx/public_html/portal/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /xxx/public_html/portal/vendor/illuminate/database/Connection.php(342): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /xxx/public_html/portal/vendor/illuminate/database/Query/Builder.php(1583): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /xxx/public_html/portal/vendor/illuminate/database/Query/Builder.php(1569): Illuminate\Database\Query\Builder->runSelect()
#4 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(624): Illuminate\Database\Query\Builder->get(Array)
#5 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(316): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(286): Illuminate\Database\Eloquent\Builder->get(Array)
#7 /xxx/public_html/portal/vendor/illuminate/database/Eloquent/Builder.php(299): Illuminate\Database\Eloquent\Builder->first(Array)
#8 /xxx/public_html/portal/modules/addons/openprovider/Controllers/Hooks/RenewHookController.php(132): Illuminate\Database\Eloquent\Builder->firstOrFail()
#9 /xxx/public_html/portal/modules/addons/openprovider/Controllers/Hooks/RenewHookController.php(192): OpenProvider\WhmcsDomainAddon\Controllers\Hooks\RenewHookController->checkScheduledTransferAtOpenprovider(Object(stdClass))
#10 /xxx/public_html/portal/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Instance.php(47): OpenProvider\WhmcsDomainAddon\Controllers\Hooks\RenewHookController->processAutorenewalSetting(Array)
#11 /xxx/public_html/portal/modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Core/Launch.php(93): WeDevelopCoffee\wPower\Core\Instance->execute('processAutorene...', Array)
#12 /xxx/public_html/portal/includes/hookfunctions.php(0): WeDevelopCoffee\wPower\Core\Launch->__call('hook_1', Array)
#13 /xxx/public_html/portal/beheer/clientsdomains.php(0): run_hook('DomainEdit', Array)
#14 {main}

**Comment by sibgatulin-danila** [comment] 2021-01-21 10:58
@muhsinozmen, hello!
I think you can try
   - Go to the page "Additional modules"
   - Activate addon openprovider
   - Click the "Configure" button.
   - Then select (or not select) any access control and click the "Save Changes" button.
The last step is to run a script to create the required tables in the database.

Will you have this problem after this algorithm?
![image](https://user-images.githubusercontent.com/51438569/105341878-36978b00-5c12-11eb-967b-b944c997da42.png)

**Comment by muhsinozmen** [comment] 2021-01-21 12:04
Hi sibgatulin-danila,

Thx for answer. I did the first steps, but where can I find the script for creating tables?

**Comment by sibgatulin-danila** [comment] 2021-01-21 12:22
@wmmuhsin sorry i meant the last step is to save the changes. This should help

Did it help?

**Comment by wmmuhsin** [comment] 2021-01-21 12:25
Sorry, it's not creating tables in mysql. Also deactivating and activating didn't help.

**Comment by sibgatulin-danila** [comment] 2021-01-22 05:24
For your case, we have a solution to create tables directly. 

There are two sql requests: 
1. to create mod_op_scheduled_domain_transfers - 
```
CREATE TABLE `mod_op_scheduled_domain_transfers` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `domain_id` int(11) DEFAULT NULL,
 `domain` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
 `status` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
 `finished_transfer_date` date NOT NULL,
 `cron_run_date` date NOT NULL,
 `run_id` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
 `created_at` timestamp NULL DEFAULT NULL,
 `updated_at` timestamp NULL DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `mod_op_scheduled_domain_transfers_domain_id_foreign` (`domain_id`),
 CONSTRAINT `mod_op_scheduled_domain_transfers_domain_id_foreign` FOREIGN KEY (`domain_id`) REFERENCES `tbldomains` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
2. to create mod_op_scheduled_domain_renewals - 
```
CREATE TABLE `mod_op_scheduled_domain_renewals` (
 `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `domain_id` int(11) NOT NULL,
 `domain` text COLLATE utf8_unicode_ci NOT NULL,
 `original_expiry_date` date NOT NULL,
 `new_expiry_date` date NOT NULL,
 `created_at` timestamp NULL DEFAULT NULL,
 `updated_at` timestamp NULL DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `mod_op_scheduled_domain_renewals_domain_id_foreign` (`domain_id`),
 CONSTRAINT `mod_op_scheduled_domain_renewals_domain_id_foreign` FOREIGN KEY (`domain_id`) REFERENCES `tbldomains` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by wmmuhsin** [comment] 2021-01-22 11:07
Thank you!! It's working now! 
Why it's not creating tables automatically? I think this should be investigated for new users.
