### ISSUE TITLE
Registration error SQL missing table/view

### ISSUE THREAD

**Issue by zerocool86** [openprovider/OP-WHMCS7#87] opened 2020-05-24 18:24 UTC
Retry Response: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbname_oxmq1.wHandles' doesn't exist (SQL: select * from `wHandles` where `data` = O:25:"OpenProvider\API\Customer":10:{s:11:"companyName";s:0:"";s:3:"vat";N;s:4:"name";O:29:"OpenProvider\API\CustomerName":4:{s:8:"initials";s:3:...........................................
//
shortened and anonymized

// please help me and others by telling, what did i miss or did i do wrong?

**Comment by soberoctober** [comment] 2020-05-25 06:26
Hello @zerocool86 

We're aware of the problem, it will be fixed in the upcoming updates to the module.

Please review the temporary workaround in this [comment](https://github.com/openprovider/OP-WHMCS7/issues/85#issuecomment-632053911).

**Comment by soberoctober** [comment] 2020-06-16 06:17
Duplicate of #85

**Closed by soberoctober** 2020-06-16 06:17 UTC
